export const DELETE_GEOPOINT = 'DELETE_GEOPOINT';
export const SORT_GEOPOINTS = 'SORT_GEOPOINTS';
export const CHANGE_POSITION = 'CHANGE_POSITION';

export const REQUESTED_GEOPOINT = 'REQUESTED_GEOPOINT';
export const REQUESTED_GEOPOINT_SUCCESS = 'REQUESTED_GEOPOINT_SUCCESS';
export const REQUESTED_GEOPOINT_FAILURE = 'REQUESTED_GEOPOINT_FAILURE';
